version: '3'

services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=feedback-widget
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local